### ISSUE TITLE
Question: Persistent IDs/Acks

### ISSUE THREAD

**Issue by daraber** [RandomEngy/fcm-push-listener#8]
If you have a long-lasting connection and/or a high throughput of notifications then you could build up a very large list of received persistent IDs. 

Is there any way of purging/ACKing seen messages other than supplying a list of received persisted IDs in the login request?
Are you expected to continuously send a login request to clear the received persistend IDs or what is the expected behavior regarding this?

**Comment by RandomEngy** [comment]
I don't know of one. Here are [all the potential messages we can send on the TLS push connection](https://github.com/RandomEngy/fcm-push-listener/blob/master/src/push.rs#L10):

```
pub enum MessageTag {
    HeartbeatPing = 0,
    HeartbeatAck,
    LoginRequest,
    LoginResponse,
    Close,
    MessageStanza,
    PresenceStanza,
    IqStanza,
    DataMessageStanza,
    BatchPresenceStanza,
    StreamErrorStanza,
    HttpRequest,
    HttpResponse,
    BindAccountRequest,
    BindAccountResponse,
    TalkMetadata,
    NumProtoTypes,
}
```

We acknowledge `HeartbeatPing` messages with `HeartbeatAck` and get messages with `DataMessageStanza` but I don't see any type for acknowledging messages right there on the connection. I think it may be a limitation of the protocol.
